name = "nb-user"
main = "worker.js"
compatibility_date = "2025-08-01"
compatibility_flags = ["nodejs_compat"]
workers_dev = true

[[d1_databases]]
binding = "DB"
database_name = "nb-some-place"
database_id = ""

[[r2_buckets]]
binding = "QR_BUCKET"
bucket_name = "nb-some-place-bucket"

[vars]
TIMEZONE = "Asia/Jakarta"
QR_PUBLIC_URL = "https://nb-user.some-user.workers.dev/qr"
